criar_tabela:
	javac app/modelo/CriadorTabela.java
	java app.modelo.CriadorTabela

compilar:
	javac --module-path "/usr/share/openjfx/lib" --add-modules javafx.controls app/visao/ProdutoGUI.java

executar:
	java --module-path "/usr/share/openjfx/lib" --add-modules javafx.controls app.visao.ProdutoGUI

# Deve ser colocado o local exato onde o JavaFX foi instalado para a compilação
